---
:ipxe:
    :images:
        :initrd: /ipxe-images/genesis-initrd.img
        :kernel: /ipxe-images/genesis-vmlinuz
    :kernel_flags: rootflags=loop root=live:/genesis.iso rootfstype=auto ro liveimg vga=791 rd_NO_LUKS rd_NO_MD rd_NO_DM console=tty0 console=ttyS1,115200
    :menu_default: intake
    :image_server: http://nexus.example.com:8888/genesis
:genesis_server: http://192.168.33.10:8000
:tasks_url: http://192.168.33.10:8888/tasks
:yum_repos:
    :epel:
        :label:   "[epel]"
        :name:    "epel"
        :descr:   "Epel"
        :baseurl: "http://repo.example.com/mrepo/RPMS.epel"
        :enabled:   1
        :priority:  1
        :gpgcheck:  0
:gem_files:
    "genesis_framework": http://192.168.33.10:8888/gem/genesis_framework
:collins:
    :host: https://collins.example.com
:ntp_server: ntp.example.com
